### ISSUE TITLE
Two classes having hashes in URL instead of slashes

### ISSUE THREAD

**Issue by martijnkersloot** [FAIRDataTeam/WHO-COVID-CRF#5]
I came across these two classes that still use # in their URL instead of / :

- http://purl.org/vodan/whocovid19crfsemdatamodel#Admission_date_at_this_facility
- http://purl.org/vodan/whocovid19crfsemdatamodel#Sternal_capillary_refill_time_greater_than_2_seconds

I think this should be updated to:

- http://purl.org/vodan/whocovid19crfsemdatamodel/Admission_date_at_this_facility
- http://purl.org/vodan/whocovid19crfsemdatamodel/Sternal_capillary_refill_time_greater_than_2_seconds

**Comment by jambelien** [comment]
Hi Martijn,

Thanks for pointing out these two hash-issues. I just resolved them and committed the changes to our repository

Cheers, Jeroen
